version: '3.1'

services:
   postgres:
     image: postgres:15.0
     restart: always
     environment:
       POSTGRES_PASSWORD: rootme
       POSTGRES_USER: auth_user
       POSTGRES_DB: auth_db
     ports:
       - 5432:5432
     volumes:
       - ./postgres-data:/var/lib/postgresql/data
